### ISSUE TITLE
Multiple CheckSuites fired for one rebase

### ISSUE THREAD

**Issue by guillaumewuip** [tibdex/github-rebase#13]
I use `github-rebase` in a Github App to perform a rebase of a Github PR and push, a lot like https://github.com/tibdex/autorebase.

Something strange seems to append with the Check Suites on my test repo (Github actions). For one only rebase process 3 Check Suites seem to be fired.

See for example https://github.com/guillaumewuip/test-github-app/pull/4/checks
![image](https://user-images.githubusercontent.com/748586/56469482-ac1d6880-643a-11e9-8f5e-c7b283fcf775.png)

3 Suites for the same commit, all on the `cherry-pick-rebase-pull-request-4-b4832f02-a5c5-4386-a9d1-efa94282f06f-ad9398f1-c1aa-4c69-9af2-f68e3e21ec63` branch that I suppose is the temporary branch `github-rebase` use to cherry-pick the commits.

Is it something known or that you already have encountered ? And do you know why the check suite run on the temporary branch and not the the head branch of the PR ?

Thanks !

**Comment by tibdex** [comment]
Hi Guillaume, you could take a look at https://github.com/tibdex/autorebase/issues/15. I hope it helps.

**Comment by guillaumewuip** [comment]
Hi @tibdex, thanks for your response.
Ok I see. I my case it's probably not easy to do at scale.

I was wondering if skipping check (with adding `skip-checks: true` in the commit message - https://help.github.com/en/articles/about-status-checks) of the commit in the temporary branch then editing the commit once on the good branch could help resolve this and make the check suite run on the real PR branch ?

**Comment by tibdex** [comment]
Partially fixed with #15 and https://github.com/tibdex/github-cherry-pick/pull/7. There will still be commits created on the temporary branch without `skip-checks: true` because these commits will end up in the orginal branch untouched and we don't want to edit the message of the cherry-picked commits.

**Comment by guillaumewuip** [comment]
Thanks for the update on this @tibdex !

I've tested the `1.1.0` version locally and it produce the same result for me (one commit on master that is not on my branch - 3 Suites fired after calling `rebasePullRequest`).

> we don't want to edit the message of the cherry-picked commits.

Why ? Is it just to be sure to not mess up with the commit message or is there another reason I don't see right now ?

**Comment by tibdex** [comment]
> Why ? Is it just to be sure to not mess up with the commit message or is there another reason I don't see right now ?

Yes it's to not mess up with the commit message. When you `git rebase` or `git cherry-pick` with the git CLI it doesn't change the commit messages. I would prefer to stay as close as possible to the CLI behavior.

> I've tested the `1.1.0` version locally and it produce the same result for me (one commit on master that is not on my branch - 3 Suites fired after calling `rebasePullRequest`).

If you still get more than 1 suite fired, it probably means the fixes are not working. I'm not using GitHub actions right now so I don't need this feature but, if you manage to make it work, I would be happy to review and merge a PR.
