### ISSUE TITLE
Not working for simple cases, no error handling

### ISSUE THREAD

**Issue by eelco** [tibdex/github-rebase#7]
It seems that if a branch has multiple adjustments of the same line of a file, `github-rebase` will always fail with an Merge Conflict error from Github.

What’s worse, the error is not handled at all, causing #6.

**Comment by tibdex** [comment]
Indeed, `github-cherry-pick` cannot cherry-pick commits editing the same line of a file. That's [a known limitation](https://github.com/tibdex/github-cherry-pick/blob/8edbb9e63a324cfb3d096a7b832f295bd3c4a929/tests/index.test.js#L285-L365) for now. I recently added [a disclaimer](https://github.com/tibdex/github-cherry-pick#disclaimer) for it.

**Comment by tibdex** [comment]
Support for more use cases has landed in https://github.com/tibdex/github-cherry-pick/commit/a636a2e0b3841e8589a1fc447c529da59b89e347.
